"""Running the generated pytest suite against the generated pipeline.

The suite is untrusted code too, so it runs in a subprocess with the same
scrubbed environment as the pipelines. It is not run through `_bootstrap`
because pytest is its own entrypoint; what it shares is the environment policy,
the timeout, and the process-group kill.

The harness writes a `conftest.py` supplying two fixtures, which is the contract
the Testing agent is told to write against:

    spark     an active SparkSession, configured by the plan
    pipeline  the generated module, already imported

Providing them rather than letting the agent construct a session is deliberate:
it keeps session configuration under the optimizer's control, and it
means a generated test cannot quietly run against a different Spark config than
the one that was validated.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from etl_migrator.domain.validation import TestRunResult
from etl_migrator.observability import get_logger
from etl_migrator.sandbox.runner import build_child_env

log = get_logger(__name__)

CONFTEST_TEMPLATE = '''\
"""Fixtures supplied by the migration harness. Not generated by an agent."""

import importlib.util
import sys

import pytest

PIPELINE_PATH = {pipeline_path!r}
INPUT_DIR = {input_dir!r}
SPARK_CONF = {spark_conf!r}


@pytest.fixture(scope="session")
def spark():
    from pyspark.sql import SparkSession

    builder = SparkSession.builder.master({master!r}).appName("etlm-generated-tests")
    for key, value in SPARK_CONF.items():
        builder = builder.config(key, value)
    session = builder.getOrCreate()
    session.sparkContext.setLogLevel("ERROR")
    yield session
    session.stop()


@pytest.fixture(scope="session")
def pipeline():
    spec = importlib.util.spec_from_file_location("etlm_pipeline_under_test", PIPELINE_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules["etlm_pipeline_under_test"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="session")
def input_dir():
    return INPUT_DIR
'''

_SUMMARY = re.compile(r"(\d+) (passed|failed|error|errors|skipped)")


def run_generated_tests(
    *,
    test_source: str,
    test_filename: str,
    pipeline_path: Path,
    input_dir: Path,
    spark_conf: dict[str, str],
    master: str = "local[2]",
    timeout_seconds: int = 900,
) -> TestRunResult:
    """Execute a generated pytest module and parse the outcome."""
    workdir = Path(tempfile.mkdtemp(prefix="etlm-tests-"))
    try:
        (workdir / "conftest.py").write_text(
            CONFTEST_TEMPLATE.format(
                pipeline_path=str(pipeline_path.resolve()),
                input_dir=str(input_dir.resolve()),
                spark_conf=dict(spark_conf),
                master=master,
            ),
            encoding="utf-8",
        )
        name = test_filename if test_filename.startswith("test_") else f"test_{test_filename}"
        (workdir / name).write_text(test_source, encoding="utf-8")

        log.info("tests.start", module=name, workdir=str(workdir))
        started = time.perf_counter()
        try:
            completed = subprocess.run(
                [
                    sys.executable, "-m", "pytest", name,
                    "-q", "--no-header", "-p", "no:cacheprovider",
                ],
                cwd=workdir,
                env=build_child_env(),
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
                check=False,
                start_new_session=True,
            )
            output = f"{completed.stdout}\n{completed.stderr}"
            duration = time.perf_counter() - started
            result = _parse(output, completed.returncode, duration)
        except subprocess.TimeoutExpired as exc:
            duration = time.perf_counter() - started
            result = TestRunResult(
                succeeded=False,
                duration_seconds=duration,
                output_tail=f"generated tests exceeded the {timeout_seconds}s limit\n"
                f"{(exc.stdout or b'').decode(errors='replace')[-2000:]}",
            )

        log.info(
            "tests.done",
            passed=result.passed,
            failed=result.failed,
            errors=result.errors,
            duration_s=round(result.duration_seconds, 2),
        )
        return result
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _parse(output: str, return_code: int, duration: float) -> TestRunResult:
    counts = {"passed": 0, "failed": 0, "error": 0, "errors": 0, "skipped": 0}
    for count, label in _SUMMARY.findall(output):
        counts[label] = int(count)
    errors = counts["error"] + counts["errors"]
    return TestRunResult(
        # `return_code == 0` is the authority; the summary line is only detail.
        # pytest exits non-zero for collection errors that print no counts at all.
        succeeded=return_code == 0,
        passed=counts["passed"],
        failed=counts["failed"],
        errors=errors,
        skipped=counts["skipped"],
        duration_seconds=duration,
        output_tail=output[-4000:],
    )
