"""Correlation id generation.

Deliberately outside `etl_migrator.domain`: that package is passed through the
Temporal workflow sandbox, and a uuid/clock helper is the one thing a workflow
must never reach for. Keeping it here makes the wrong call inconvenient.

A migration id is generated by whoever *submits* a migration, never by the
workflow, and doubles as the Temporal workflow id — which makes resubmission
idempotent rather than duplicating a run.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime


def new_migration_id() -> str:
    """Sortable, human-scannable, unique: `mig-20260810T151737-40d6054c`."""
    return f"mig-{datetime.now(UTC):%Y%m%dT%H%M%S}-{uuid.uuid4().hex[:8]}"
