"""Pure, dependency-free domain models.

This package imports nothing outside pydantic and the stdlib. That is a hard
rule: it is on Temporal's sandbox passthrough list, which is
only safe if importing it can have no side effects.
"""

from etl_migrator.domain import lifecycle
from etl_migrator.domain.artifacts import (
    CodeGenResult,
    Finding,
    GeneratedCode,
    MigrationRecord,
    StageRecord,
    StaticAnalysisReport,
)
from etl_migrator.domain.enums import (
    DataFormat,
    JoinType,
    MigrationStage,
    RiskCategory,
    RiskLevel,
    Severity,
    SourceLanguage,
    TransformKind,
    ValidationStatus,
    WriteMode,
)
from etl_migrator.domain.errors import (
    AgentContractError,
    ConfigurationError,
    MigrationError,
    NonRetryableMigrationError,
    SandboxError,
    ScriptExhaustedError,
    StaticGateError,
    UnsupportedSourceError,
)
from etl_migrator.domain.messages import (
    DEFAULT_APPROVAL_TIMEOUT_SECONDS,
    AgentTelemetry,
    ApprovalDecision,
    CodegenInput,
    CodegenOutput,
    DiscoveryInput,
    DiscoveryOutput,
    MigrationStatus,
    MigrationWorkflowInput,
    PersistInput,
    PersistOutput,
    PlanningInput,
    PlanningOutput,
    StaticAnalysisInput,
    StaticAnalysisOutput,
    ToolResult,
)
from etl_migrator.domain.plan import (
    ExecutionStrategy,
    MigrationPlan,
    PlanStep,
    SemanticDifference,
    ValidationPlan,
)
from etl_migrator.domain.repair import (
    RepairAttempt,
    RepairLedger,
    RepairOutcome,
    RepairProposal,
    RepairStrategy,
    code_fingerprint,
)
from etl_migrator.domain.spec import (
    AggregationDetail,
    BusinessRule,
    ColumnSpec,
    DataSink,
    DataSource,
    JoinDetail,
    MigrationRisk,
    MigrationSpec,
    StrictModel,
    Transformation,
)
from etl_migrator.domain.validation import (
    CheckResult,
    ColumnStat,
    DatasetStats,
    Difference,
    ExecutionResult,
    GeneratedTests,
    TestRunResult,
    ValidationDiagnosis,
    ValidationOutcome,
    ValidationReport,
)

__all__ = [
    "DEFAULT_APPROVAL_TIMEOUT_SECONDS",
    "AgentContractError",
    "AgentTelemetry",
    "AggregationDetail",
    "ApprovalDecision",
    "BusinessRule",
    "CheckResult",
    "CodeGenResult",
    "CodegenInput",
    "CodegenOutput",
    "ColumnSpec",
    "ColumnStat",
    "ConfigurationError",
    "DataFormat",
    "DataSink",
    "DataSource",
    "DatasetStats",
    "Difference",
    "DiscoveryInput",
    "DiscoveryOutput",
    "ExecutionResult",
    "ExecutionStrategy",
    "Finding",
    "GeneratedCode",
    "GeneratedTests",
    "JoinDetail",
    "JoinType",
    "MigrationError",
    "MigrationPlan",
    "MigrationRecord",
    "MigrationRisk",
    "MigrationSpec",
    "MigrationStage",
    "MigrationStatus",
    "MigrationWorkflowInput",
    "NonRetryableMigrationError",
    "PersistInput",
    "PersistOutput",
    "PlanStep",
    "PlanningInput",
    "PlanningOutput",
    "RepairAttempt",
    "RepairLedger",
    "RepairOutcome",
    "RepairProposal",
    "RepairStrategy",
    "RiskCategory",
    "RiskLevel",
    "SandboxError",
    "ScriptExhaustedError",
    "SemanticDifference",
    "Severity",
    "SourceLanguage",
    "StageRecord",
    "StaticAnalysisInput",
    "StaticAnalysisOutput",
    "StaticAnalysisReport",
    "StaticGateError",
    "StrictModel",
    "TestRunResult",
    "ToolResult",
    "TransformKind",
    "Transformation",
    "UnsupportedSourceError",
    "ValidationDiagnosis",
    "ValidationOutcome",
    "ValidationPlan",
    "ValidationReport",
    "ValidationStatus",
    "WriteMode",
    "code_fingerprint",
    "lifecycle",
]
