"""Wire contracts: activity inputs/outputs, workflow input, signals, queries.

Kept separate from the artifacts they carry because these are *protocol*. Once a
workflow is running in production, changing one of these shapes is a versioning
event; changing a field on `MigrationSpec` is not. Every activity therefore
takes exactly one argument and returns exactly one value, which is what makes a
field addition backwards compatible.
"""

from __future__ import annotations

from pydantic import Field

from etl_migrator.domain.artifacts import (
    CodeGenResult,
    GeneratedCode,
    MigrationRecord,
    StageRecord,
    StaticAnalysisReport,
)
from etl_migrator.domain.delivery import (
    ClaimAudit,
    DeliveryDecision,
    PullRequestNarrative,
)
from etl_migrator.domain.enums import MigrationStage, RiskLevel
from etl_migrator.domain.optimization import (
    DEFAULT_MIN_SPEEDUP,
    DEFAULT_RUNS,
    DEFAULT_WARMUPS,
    BenchmarkResult,
    OptimizationAttempt,
    OptimizationProposal,
)
from etl_migrator.domain.plan import ExecutionStrategy, MigrationPlan
from etl_migrator.domain.repair import RepairAttempt, RepairProposal
from etl_migrator.domain.spec import MigrationSpec, StrictModel
from etl_migrator.domain.validation import (
    GeneratedTests,
    ValidationDiagnosis,
    ValidationReport,
)

#: One week. Long enough that a HIGH-risk migration can wait for a human who is
#: on holiday, which is exactly the scenario durable execution exists for.
DEFAULT_APPROVAL_TIMEOUT_SECONDS = 7 * 24 * 60 * 60


# --------------------------------------------------------------------------
# Telemetry
# --------------------------------------------------------------------------
class ToolResult(StrictModel):
    name: str
    is_error: bool
    preview: str


class AgentTelemetry(StrictModel):
    """Evidence that an agent did what it claims. Feeds Prometheus."""

    agent: str
    tools_used: list[str] = Field(default_factory=list)
    llm_turns: int = 0
    duration_seconds: float = 0.0
    gate_iterations: int | None = Field(
        default=None, description="Code-generation only: gate submissions the agent needed."
    )
    tool_results: list[ToolResult] = Field(default_factory=list)


# --------------------------------------------------------------------------
# Workflow input
# --------------------------------------------------------------------------
class MigrationWorkflowInput(StrictModel):
    """Input to `ETLMigrationWorkflow`.

    `migration_id` is generated by the caller, not the workflow, and is used as
    the Temporal workflow id. That gives deduplication for free: submitting the
    same migration id twice attaches to the running execution instead of
    starting a second one.
    """

    migration_id: str
    source_path: str
    input_dir: str
    output_filename: str
    scenario: str = Field(
        default="customer_pipeline",
        description="Fixture scenario when the scripted provider is configured.",
    )
    approval_timeout_seconds: int = Field(
        default=DEFAULT_APPROVAL_TIMEOUT_SECONDS, ge=1
    )
    run_generated_tests: bool = Field(
        default=True, description="Generate and execute a pytest suite during validation."
    )
    validation_timeout_seconds: int = Field(
        default=2 * 60 * 60,
        ge=60,
        description="Ceiling for the whole validation child workflow, which executes "
        "both pipelines and may run Spark for a long time.",
    )
    repair_enabled: bool = Field(
        default=True, description="Attempt autonomous repair when validation fails."
    )
    max_repair_attempts: int = Field(
        default=3,
        ge=1,
        le=10,
        description="Distinct strategies to try. Small on purpose: an agent that "
        "cannot fix it in three genuinely different ways is not converging.",
    )
    repair_timeout_seconds: int = Field(default=6 * 60 * 60, ge=60)
    optimize_enabled: bool = Field(
        default=True, description="Benchmark and attempt optimisation once correct."
    )
    max_optimization_attempts: int = Field(default=2, ge=1, le=5)
    benchmark_runs: int = Field(default=DEFAULT_RUNS, ge=2, le=20)
    min_speedup: float = Field(
        default=DEFAULT_MIN_SPEEDUP,
        gt=1.0,
        description="Below this the change is not worth the review burden even if real.",
    )
    optimization_timeout_seconds: int = Field(default=4 * 60 * 60, ge=60)
    execution_task_queue: str = Field(
        default="",
        description="Task queue for the activities that execute untrusted generated "
        "code. Empty means the workflow's own queue, which is correct for a single "
        "worker; set it and those activities are dispatched to a worker deployed "
        "with no internet egress (see k8s/).",
    )
    deliver_enabled: bool = Field(
        default=True,
        description="Open a pull request when the migration finishes. Runs on "
        "failure too — see `decide_delivery` for what each outcome gets.",
    )
    delivery_branch_prefix: str = "etl-migration"
    delivery_directory: str = "migrations"
    delivery_timeout_seconds: int = Field(default=30 * 60, ge=60)


# --------------------------------------------------------------------------
# Signals
# --------------------------------------------------------------------------
class ApprovalDecision(StrictModel):
    """Sent to the `approve` signal to release or reject a paused migration."""

    approved: bool
    actor: str = Field(description="Who decided. Recorded in the migration record and the PR.")
    reason: str | None = None


# --------------------------------------------------------------------------
# Queries
# --------------------------------------------------------------------------
class MigrationStatus(StrictModel):
    """Cheap, queryable view of a running migration.

    Deliberately small: a status poller should not pull the whole record, and a
    query response has a size limit.
    """

    migration_id: str
    stage: MigrationStage
    risk: RiskLevel
    awaiting_approval: bool = False
    approval: ApprovalDecision | None = None
    finished: bool = False
    failed: bool = False
    failure_reason: str | None = None
    stages: list[StageRecord] = Field(default_factory=list)


# --------------------------------------------------------------------------
# Activity inputs / outputs
# --------------------------------------------------------------------------
class DiscoveryInput(StrictModel):
    migration_id: str
    source_path: str
    input_dir: str
    scenario: str


class DiscoveryOutput(StrictModel):
    spec: MigrationSpec
    telemetry: AgentTelemetry


class PlanningInput(StrictModel):
    migration_id: str
    input_dir: str
    scenario: str
    spec: MigrationSpec


class PlanningOutput(StrictModel):
    plan: MigrationPlan
    telemetry: AgentTelemetry


class CodegenInput(StrictModel):
    migration_id: str
    scenario: str
    output_filename: str
    spec: MigrationSpec
    plan: MigrationPlan


class CodegenOutput(StrictModel):
    code: GeneratedCode
    telemetry: AgentTelemetry
    gate_iterations: int = Field(default=1, ge=1)


class StaticAnalysisInput(StrictModel):
    migration_id: str
    code: GeneratedCode
    gate_iterations: int = Field(default=1, ge=1)


class StaticAnalysisOutput(StrictModel):
    """The independent gate verdict.

    Returned as *data* rather than raised as an error on purpose. A failing gate
    is a legitimate outcome the workflow must reason about, since it routes to the
    repair loop, and an exception would hand that decision to a retry
    policy instead.
    """

    result: CodeGenResult

    @property
    def passed(self) -> bool:
        return self.result.static_analysis.passed

    @property
    def report(self) -> StaticAnalysisReport:
        return self.result.static_analysis


class PersistInput(StrictModel):
    migration_id: str
    record_json: str = Field(
        description="Serialised MigrationRecord. Passed as JSON so the activity "
        "writes exactly the state the workflow holds, with no re-derivation."
    )
    telemetry: list[AgentTelemetry] = Field(default_factory=list)


class PersistOutput(StrictModel):
    artifact_dir: str
    files_written: list[str] = Field(default_factory=list)


# --------------------------------------------------------------------------
# Validation stage
# --------------------------------------------------------------------------
class ValidationWorkflowInput(StrictModel):
    """Input to `ValidationWorkflow`, the child that decides correctness."""

    migration_id: str
    legacy_source_path: str
    input_dir: str
    scenario: str
    spec: MigrationSpec
    plan: MigrationPlan
    code: GeneratedCode
    run_generated_tests: bool = Field(
        default=True,
        description="Generating and running a pytest suite roughly doubles the stage's "
        "wall time; it can be skipped for a fast correctness-only pass.",
    )
    execution_task_queue: str = Field(
        default="",
        description="Task queue for the activities that execute untrusted generated "
        "code. Empty means the workflow's own queue, which is correct for a single "
        "worker; set it and those activities are dispatched to a worker deployed "
        "with no internet egress (see k8s/).",
    )


class LegacyExecutionInput(StrictModel):
    migration_id: str
    source_path: str
    input_dir: str


class SparkExecutionInput(StrictModel):
    migration_id: str
    input_dir: str
    code: GeneratedCode
    execution_strategy: ExecutionStrategy | None = None
    output_name: str = "candidate_output"


class OutputValidationInput(StrictModel):
    migration_id: str
    reference_path: str
    candidate_path: str
    plan: MigrationPlan


class TestGenerationInput(StrictModel):
    migration_id: str
    scenario: str
    spec: MigrationSpec
    plan: MigrationPlan
    code: GeneratedCode
    filename: str = "test_generated_pipeline.py"


class TestGenerationOutput(StrictModel):
    tests: GeneratedTests
    static_analysis: StaticAnalysisReport
    telemetry: AgentTelemetry
    gate_iterations: int = Field(default=1, ge=1)


class TestExecutionInput(StrictModel):
    migration_id: str
    tests: GeneratedTests
    code: GeneratedCode
    input_dir: str
    execution_strategy: ExecutionStrategy | None = None


class DiagnosisInput(StrictModel):
    migration_id: str
    scenario: str
    report: ValidationReport
    plan: MigrationPlan


class DiagnosisOutput(StrictModel):
    diagnosis: ValidationDiagnosis
    telemetry: AgentTelemetry



# --------------------------------------------------------------------------
# Repair loop
# --------------------------------------------------------------------------
class RepairWorkflowInput(StrictModel):
    """Input to `RepairWorkflow`, the bounded fix-and-revalidate loop."""

    migration_id: str
    legacy_source_path: str
    input_dir: str
    scenario: str
    spec: MigrationSpec
    plan: MigrationPlan
    code: GeneratedCode = Field(description="The code that failed validation.")
    report: ValidationReport = Field(description="The measured failure being repaired.")
    diagnosis: ValidationDiagnosis | None = None
    max_attempts: int = Field(default=3, ge=1, le=10)
    run_generated_tests: bool = True
    execution_task_queue: str = Field(
        default="",
        description="Task queue for the activities that execute untrusted generated "
        "code. Empty means the workflow's own queue, which is correct for a single "
        "worker; set it and those activities are dispatched to a worker deployed "
        "with no internet egress (see k8s/)."
    )


class RepairProposalInput(StrictModel):
    migration_id: str
    scenario: str
    attempt: int = Field(ge=1)
    max_attempts: int = Field(ge=1)
    plan: MigrationPlan
    code: GeneratedCode
    report: ValidationReport
    diagnosis: ValidationDiagnosis | None = None
    history: list[RepairAttempt] = Field(default_factory=list)


class RepairProposalOutput(StrictModel):
    proposal: RepairProposal
    telemetry: AgentTelemetry
    gate_iterations: int = Field(default=1, ge=1)



# --------------------------------------------------------------------------
# Optimisation
# --------------------------------------------------------------------------
class OptimizationWorkflowInput(StrictModel):
    """Input to `OptimizationWorkflow`, which runs only on a correct migration."""

    migration_id: str
    legacy_source_path: str
    input_dir: str
    scenario: str
    spec: MigrationSpec
    plan: MigrationPlan
    code: GeneratedCode
    max_attempts: int = Field(default=2, ge=1, le=5)
    benchmark_runs: int = Field(default=DEFAULT_RUNS, ge=2, le=20)
    benchmark_warmups: int = Field(default=DEFAULT_WARMUPS, ge=0, le=5)
    min_speedup: float = Field(default=DEFAULT_MIN_SPEEDUP, gt=1.0)
    execution_task_queue: str = Field(
        default="",
        description="Task queue for the activities that execute untrusted generated "
        "code. Empty means the workflow's own queue, which is correct for a single "
        "worker; set it and those activities are dispatched to a worker deployed "
        "with no internet egress (see k8s/).",
    )


class BenchmarkInput(StrictModel):
    migration_id: str
    label: str
    code: GeneratedCode
    input_dir: str
    execution_strategy: ExecutionStrategy | None = None
    runs: int = Field(default=DEFAULT_RUNS, ge=1, le=20)
    warmups: int = Field(default=DEFAULT_WARMUPS, ge=0, le=5)


class OptimizationProposalInput(StrictModel):
    migration_id: str
    scenario: str
    attempt: int = Field(ge=1)
    max_attempts: int = Field(ge=1)
    plan: MigrationPlan
    code: GeneratedCode
    input_dir: str
    baseline: BenchmarkResult
    history: list[OptimizationAttempt] = Field(default_factory=list)


class OptimizationProposalOutput(StrictModel):
    proposal: OptimizationProposal
    telemetry: AgentTelemetry
    gate_iterations: int = Field(default=1, ge=1)


class PullRequestNarrativeInput(StrictModel):
    """Input to the delivery agent activity."""

    migration_id: str
    scenario: str
    record: MigrationRecord
    decision: DeliveryDecision
    previous_audit: ClaimAudit | None = Field(
        default=None,
        description="A failed audit from the previous attempt, so a rewrite is "
        "directed at the specific figures that were wrong.",
    )


class PullRequestNarrativeOutput(StrictModel):
    narrative: PullRequestNarrative
    audit: ClaimAudit = Field(
        description="Run in the activity, against the same record the workflow holds. "
        "The workflow decides what to do about a failure; it never re-derives it."
    )
    telemetry: AgentTelemetry


class DeliverPullRequestInput(StrictModel):
    """Everything needed to put a migration on a branch and open a PR.

    Carries the whole record because the evidence half of the body is rendered
    from it, deterministically, inside the activity.
    """

    migration_id: str
    record: MigrationRecord
    decision: DeliveryDecision
    narrative: PullRequestNarrative
    branch: str
    directory: str = "migrations"
    base: str | None = None


class DeliveryWorkflowInput(StrictModel):
    """Input to `DeliveryWorkflow`.

    Carries the whole record: the delivery decision and the evidence half of the
    PR body are both derived from it, so passing a summary would mean deriving
    them from something lossier than what the parent already holds.
    """

    migration_id: str
    scenario: str
    record: MigrationRecord
    branch_prefix: str = "etl-migration"
    directory: str = "migrations"
    max_narrative_revisions: int = Field(default=2, ge=0, le=5)
